### ISSUE TITLE
Proposal: Include passing of parameters to python function writePdf 

### ISSUE THREAD

**Issue by germinator1512** [berthertogen/weasyprint.wrapped#42]
Weasyprint supports various parameters in its writePdf function, e.g. 
![grafik](https://user-images.githubusercontent.com/65281921/219650607-966b74ce-3b04-43d9-8e67-736cb2cfcebd.png)

Problem is, when including images, the pdf file size is very high. Using the "optimize_size" parameter would address that problem.

**Comment by berthertogen** [comment]
Nice suggestion, we'll have to look into how they support passing these parameters through the cli (because this package uses the cli).
If you feel up for the task you can always create a PR ;). I'll have a look at it whenever I have some spare time. Might be this weekend.

**Comment by germinator1512** [comment]
Ive tried it with the Example Project in your repository (dotnet 6) and it works. Pdf with a 5 MB Image has a total Size of 3.35 mb.
When using the exact same code in dotnet 7, the pdf file has 30 MB. When I change the dotnet version in your project from 6 to 7, the file size also increases. When I go back to dotnet version 6, the file stays this big. I'm totally confused what is going on . Do you have any idea?

**Comment by berthertogen** [comment]
I wasn't able to test the .net 7 upgrade but added the additional parameters in the latest release #46
