### ISSUE TITLE
Could weasyprint be upgraded frm v61 to latest version?

### ISSUE THREAD

**Issue by vlasto77** [berthertogen/weasyprint.wrapped#56]
Package contains weasyprint v61 but there is newer one with better css support.

**Comment by berthertogen** [comment]
Hey @vlasto77 sorry for the late reply! I've updated the version to 62.3.

**Comment by snt0** [comment]
Hi, I see this has been merged into main, but has yet to be released, so I cannot use Weasyprint 62.3 features through the Nuget package. Is there a workaround here, or perhaps are you able to make a new release?

**Comment by berthertogen** [comment]
Het @snt0, first of all best wishes for 2025 ;) and thanks for using the library.
I've just made the [v7.0.0](https://github.com/berthertogen/weasyprint.wrapped/releases/tag/v7.0.1) release!
